accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from .views import (
    RegisterView,
    ProfileView,
    RequestTeacherView,
    CourseCreateView,
    MyCoursesView,
    DeleteCourse,
    LeaveCourse,
    CreateArticleView,
    DeleteArticleView,
    ArticleListView,
    CreateHandoutView,
    PollListView,
    CreatePollView,
    AddChoiceView
    )

app_name = 'accounts'

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("teacher/request/", RequestTeacherView.as_view(), name="teacher-request"),
    path("teacher/course/craete/", CourseCreateView.as_view(), name="create-course"),
    path("course/", MyCoursesView.as_view(), name="list-courses"),
    path("course/register/<int:course_id>/", MyCoursesView.as_view(), name="register-courses"),
    path("course/delete/<int:pk>/", DeleteCourse.as_view(), name="delete-course"),
    path("course/leave/<int:pk>/", LeaveCourse.as_view(), name="leave-course"),
    path("article/", ArticleListView.as_view(), name="list-articles"),
    path("article/create/", CreateArticleView.as_view(), name="create-article"),
    path("article/delete/<int:pk>/", DeleteArticleView.as_view(), name="delete-article"),
    path("handout/create/", CreateHandoutView.as_view(), name="create-handout"),
    path("poll/", PollListView.as_view(), name="list-poll"),
    path("poll/create/", CreatePollView.as_view(), name="create-poll"),
    path("poll/<int:poll_id>/", AddChoiceView.as_view(), name="add-choice"),
]

home/urls.py
from django.urls import path
from .views import Index,DetailNewsView,NewsListView,DetailArticleView,ArticleListView,HandoutListView,CourseListView,DetailCourseView,DetailPollView

app_name = 'home'

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("news/<int:pk>/", DetailNewsView.as_view(), name="detail-news"),
    path("news/", NewsListView.as_view(), name="list-news"),
    path("article/<int:pk>/", DetailArticleView.as_view(), name="detail-article"),
    path("article/", ArticleListView.as_view(), name="list-article"),
    path("handout/", HandoutListView.as_view(), name="list-handout"),
    path("course/", CourseListView.as_view(), name="list-course"),
    path("course/<int:pk>/", DetailCourseView.as_view(), name="detail-course"),
    path("polls/<int:pk>/", DetailPollView.as_view(), name="detail-poll"),
]

institute_programming/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('account/', include('accounts.urls',namespace='accounts')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User

class News(models.Model):
    title = models.CharField(max_length=64,verbose_name='عنوان')
    body = models.TextField(verbose_name='بدنه')
    created = models.DateTimeField(auto_now_add=True,verbose_name='زمان ایجاد')

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'خبر'
        verbose_name_plural  = 'اخبار'

class Article(models.Model):
    author = models.ForeignKey(User,related_name='article',verbose_name='نویسنده',on_delete=models.CASCADE)
    title = models.CharField(max_length=64,verbose_name='عنوان',unique=True)
    body = models.TextField(verbose_name='متن مقاله')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural  = 'مقالات'

class Handout(models.Model):
    title = models.CharField(max_length=64,verbose_name='عنوان')
    pdf = models.FileField(upload_to='pdf',verbose_name='فایل پی دی اف')
    created = models.DateTimeField(auto_now_add=True,verbose_name='زمان ایجاد')

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'جزوه'
        verbose_name_plural  = 'جزوات'

home/forms.py
from django import forms
from accounts.models import Poll

# class PollForm(forms.ModelForm):
    
#     class Meta:
#         model = Poll
#         fields = ("",)

home/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.views.generic import DetailView,ListView,FormView
from .models import News,Article,Handout
from accounts.models import Course,Poll,Choice,Vote
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseNotFound,HttpResponseForbidden

class Index(View):
    def get(self,request):
        last_news = News.objects.all().order_by('-created')[:5]
        last_articles = Article.objects.all().order_by('-created')[:5]
        last_handout = Handout.objects.all().order_by('-created')[:5]
        last_courses = Course.objects.all().order_by('-created')[:5]

        all_polls = None
        if request.user.is_authenticated:
            courses_user = request.user.courses.all()
            all_polls = Poll.objects.filter(Q(for_course__in=courses_user) & ~Q(votes__user=request.user))

        context = {
            'last_news':last_news,
            'last_articles':last_articles,
            'last_handout':last_handout,
            'last_courses':last_courses,
            'all_polls':all_polls,
        }

        return render(request,'home/index.html',context)

class DetailNewsView(DetailView):
    template_name = 'home/detail_news.html'
    model = News
    context_object_name = 'news'

class NewsListView(ListView):
    template_name = 'home/list_news.html'
    model = News
    context_object_name = 'all_news'

class DetailArticleView(DetailView):
    template_name = 'home/detail_article.html'
    model = Article
    context_object_name = 'article'

class ArticleListView(ListView):
    template_name = 'home/list_article.html'
    model = Article
    context_object_name = 'all_articles'

class HandoutListView(ListView):
    template_name = 'home/list_handout.html'
    model = Handout
    context_object_name = 'all_handout'

class CourseListView(ListView):
    template_name = 'home/list_course.html'
    model = Course
    context_object_name = 'all_courses'

class DetailCourseView(DetailView):
    template_name = 'home/detail_course.html'
    model = Course
    context_object_name = 'course'

class DetailPollView(LoginRequiredMixin,View):
    def dispatch(self, request,pk, *args, **kwargs):
        try:
            poll = Poll.objects.get(pk=pk)
            if Vote.objects.filter(poll=poll,user=request.user).exists():
                return HttpResponseForbidden()
        except:
            return HttpResponseNotFound()

        return super().dispatch(request,pk, *args, **kwargs)


    def get(self, request, pk):
        poll = Poll.objects.get(pk=pk)
        return render(
            request,
            template_name='home/detail_poll.html',
            context={
                "poll": poll,
            }
        )
    
    def post(self,request,pk):
        requestData = request.POST

        choice_id = requestData.get('choice_id')

        poll = Poll.objects.get(id=pk)
        choice = Choice.objects.get(id=choice_id)
        Vote.objects.create(
            poll=poll,
            choice=choice,
            user=request.user,
        )

        return redirect('home:index')

home/templates/home/detail_article.html
{% extends 'base.html' %}
{% load humanize %}

{% block body %}
    <div class="col-8 m-auto mt-5 box-content p-5" dir='rtl'>
        <h3 class='float-start col-9'>{{ article.title }}</h3> 
        <div class='float-end col-3 d-flex flex-column justify-content-around '>
            <small class="text-success">نویسنده : {{ article.author }}</small> 
            <small class="text-primary">زمان ایجاد : {{ article.created | timesince }} قبل</small>
        </div>
        <div class="clearfix"></div>
        <hr>
        <p>{{article.body | linebreaks }}</p>
    </div>
{% endblock body  %}

home/templates/home/detail_course.html
{% extends 'base.html' %}

{% block body %}
    <div class="col-8 m-auto mt-5 box-content p-5" dir='rtl'>
        <img class="img-thumbnail w-50 d-block mx-auto" src="{{ course.thumbnail.url }}">
        <h3 class='float-start col-10'>{{ course.name }}</h3> 

        <div class='float-end col-2 d-flex flex-column justify-content-around '>
            <small class="text-success">استاد : {{ course.teacher }}</small> 
            <small class="text-primary">تاریخ شروع دوره: {{ course.start | date }}</small>
        </div>
        <div class="clearfix"></div>
        <hr>
        <h5 class="float-start">توضیحات : </h5>
        <p> {{course.description | linebreaks }} </p>
        
        {% if request.user.is_authenticated %}
            {% if not request.user.teacher %}
                
                {% if course in request.user.courses.all %}
                <a class="btn btn-success w-100 disabled">شما در این دوره ثبت نام کردید</a>
                {% else %}
                <a href="{% url 'accounts:register-courses' course.pk %}" class="btn btn-primary w-100">ثبت نام در دوره</a>
                {% endif %}
            {% endif %}
        {% else %}
        <a href="{% url 'accounts:login' %}" class="btn btn-secondary w-100">برای ثبت نام در دوره اول لاگین کنید</a>
        {% endif %}

            
    </div>
{% endblock body  %}

home/templates/home/detail_news.html
{% extends 'base.html' %}

{% block body %}
    <div class="col-8 m-auto mt-5 box-content p-5" dir='rtl'>
        <h3>{{news.title}}</h3>
        <hr>
        <p>{{news.body | linebreaks }}</p>
        <p class='text-primary font-italic'><span>{{news.created | date:'f' }} | {{news.created | date:'SHORT_DATE_FORMAT' }}</span></p>
    </div>
{% endblock body  %}

home/templates/home/detail_poll.html
{% extends 'base.html' %}

{% block body %}
    <div class="col-8 m-auto mt-5 box-content p-5" dir='rtl'>
        <h3>{{poll.name}}</h3>
        <small>برای دوره {{poll.for_course.name}}</small>
        <hr>
        <form method="post">
            {% csrf_token %}
            {% for choice in poll.choices.all %}
            <div class="form-check">
                <input class="form-check-input" type="radio" name="choice_id" id="{{ choice.id }}" value="{{ choice.id }}">
                <label class="form-check-label" for="{{ choice.id }}">
                  {{ choice.name }}
                </label>
            </div>
            {% endfor %}
            <button class="btn btn-success w-100">ارسال نظرسنجی</button>
        </form>
    </div>
{% endblock body  %}

home/templates/home/index.html
{% extends 'base.html' %}
{% load humanize %}

{% block body %}
<main class="mt-2 m-1">
    <div class="d-flex flex-column float-end col-3">
        <section class="box" dir="rtl">
            <div class="item-box text-center bg-primary text-light rounded-top-3">جدیدترین اخبار</div>
            <!-- News -->
            {% for news in last_news %}
            <hr class='m-0'>
            <a href='{% url "home:detail-news" news.id %}' class="item-box d-flex justify-content-between">
                <span>{{news.title}}</span>
                <span>{{news.created | date:'f' }} | {{news.created | date:'SHORT_DATE_FORMAT' }}</span>
            </a>
            <hr class='m-0'>
            {% empty %}
            <p class="item-box d-block text-center p-2">
                در حال حاضر خبری بارگذاری نشده
            </p>
            {% endfor %}
        </section>
        <section class="box" dir="rtl">
            <div class="item-box text-center bg-primary text-light rounded-top-3">جدیدترین جزوه ها</div>
            <!-- handout -->
            <hr class='m-0'>
            {% for handout in last_handout %}
            <a href='{{ handout.pdf.url }}' class="item-box d-block">
                {{handout.title}}
            </a>
            <hr class='m-0'>
            {% empty %}
            <p class="item-news d-block text-center p-2">
                در حال حاضر جزوه ای بارگذاری نشده
            </p>
            {% endfor %}
        </section>
        <section class="box" dir="rtl">
            <div class="item-box text-center bg-primary text-light rounded-top-3">جدیدترین دوره ها</div>
            <!-- handout -->
            <hr class='m-0'>
            {% for course in last_courses %}
            <a href="{% url 'home:detail-course' course.pk %}" class="item-box d-block">
                {{course.name}}
            </a>
            <hr class='m-0'>
            {% empty %}
            <p class="item-news d-block text-center p-2">
                در حال حاضر دوره ای درحال برکزاری نمی باشد
            </p>
            {% endfor %}
        </section>
        {% if request.user.is_authenticated %}
            <section class="box" dir="rtl">
                <div class="item-box text-center bg-primary text-light rounded-top-3">نظر سنجی های مربوط به شما</div>
                <!-- handout -->
                <hr class='m-0'>
                {% for poll in all_polls %}
                <a href="{% url 'home:detail-poll' poll.pk %}" class="item-box d-block">
                    {{poll.name}}
                </a>
                <hr class='m-0'>
                {% empty %}
                <p class="item-news d-block text-center p-2">
                    نظر سنجی پاسخ داده نشده ای برای شما وجود ندارد
                </p>
                {% endfor %}
            </section>
        {% endif %}
    </div>

    <section class="col-8 float-start box p-3 ms-5" dir="rtl">
        <div class="item-box text-center bg-dark text-light">اخرین مقالات</div>
        <!-- Artiles -->
        {% for article in last_articles %}
        <div class="col-10 mx-auto my-4 p-3 border border-1 border-info rounded">
            <h3><a href="{% url 'home:detail-article' article.pk %}" class="link">{{article.title}}</a></h3>
            <hr>
            <p>{{article.body | truncatechars:300 | linebreaks}} <a href="{% url 'home:detail-article' article.pk %}" class='btn btn-sm btn-primary'>خواندن ادامه</a></p>
            <small class="float-start text-dark">{{article.created | timesince}} قبل</small>
            <small class="float-end text-success">نویسنده : {{article.author}}</small>
            <div class="clearfix"></div>
        </div>
        {% empty %}
        <p class="item-news d-block text-center p-2">
            در حال حاضر مقاله ای بارگذاری نشده
        </p>
        {% endfor %}
    </section>
</main>
{% endblock body %}

home/templates/home/list_article.html
{% extends 'base.html' %}

{% block body %}
<div dir="rtl" class="col-9 box mx-auto mt-5 p-4">
    {% for article in all_articles %}
    <div class='custom-shadow p-3 radius col-10 mx-auto my-2'>
        <h3><a href="{% url 'home:detail-article' article.pk %}" class="link">{{article.title}}</a></h3>
        <hr>
        <p>{{article.body | truncatechars:300 | linebreaks}} <a href="{% url 'home:detail-article' article.pk %}" class='btn btn-sm btn-primary'>خواندن ادامه</a></p>
        <small class="float-start text-primary">{{article.created | timesince}} قبل</small>
        <small class="float-end text-success">نویسنده : {{article.author}}</small>
        <div class='clearfix'></div>
    </div>
    {% empty %}
    <p class="item-box d-block">
        در حال حاضر مقاله ای بارگذاری نشده
    </p>
    {% endfor %}
</div>
{% endblock body %}

home/templates/home/list_course.html
{% extends 'base.html' %}

{% block body %}
<div dir="rtl" class="col-9 box mx-auto mt-5 p-4 d-flex flex-wrap">
    {% for course in all_courses %}
    <div class='custom-shadow p-3 radius col-3 mx-auto my-2'>
        <img class="img-thumbnail w-100" src="{{ course.thumbnail.url }}" style="height:250px;">
        <h3><a href="{% url 'home:detail-course' course.pk %}" class="link">{{course.name}}</a></h3>
        <hr>
        <small class="float-start text-primary">تاریخ شروع : {{course.start | date}}</small>
        <small class="float-end text-success">استاد دوره : {{course.teacher}}</small>
        <div class='clearfix'></div>
    </div>
    <div class='m-1'></div>
    {% empty %}
    <p class="item-box d-block">
            درحال حاضر دور ای برای ثبت نام وجود ندارد
    </p>
    {% endfor %}
</div>
{% endblock body %}

home/templates/home/list_handout.html
{% extends 'base.html' %}

{% block body %}
<div dir="rtl" class="col-8 box mx-auto mt-5 p-3">
    <h4>لیست جزوات (برای دانلود کلیک کنید)</h4>
    <hr>
    <div class=" border border-info col-11 mx-auto">
    {% for handout in all_handout %}
    <a href='{{ handout.pdf.url }}' class="item-box d-block">
        {{handout.title}}
    </a>
    <hr class="m-1">
    {% empty %}
    <p class="item-box d-block">
        در حال حاضر جزوه ای بارگذاری نشده
    </p>
    {% endfor %}
</div>
</div>
{% endblock body %}

home/templates/home/list_news.html
{% extends 'base.html' %}

{% block body %}
<div dir="rtl" class="col-8 box mx-auto mt-5">
    {% for news in all_news %}
    <a href='{% url "home:detail-news" news.id %}' class="item-box d-flex justify-content-between">
        <span>{{news.title}}</span>
        <span>{{news.created | date:'f' }} | {{news.created | date:'SHORT_DATE_FORMAT' }}</span>
    </a>
    <hr class='m-1'>
    {% empty %}
    <p class="item-box d-block">
        در حال حاضر خبری بارگذاری نشده
    </p>
    {% endfor %}
</div>
{% endblock body %}