accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from .views import (
    RegisterView,
    ProfileView,
    RequestTeacherView,
    CourseCreateView,
    MyCoursesView,
    DeleteCourse,
    LeaveCourse,
    CreateArticleView,
    DeleteArticleView,
    ArticleListView,
    CreateHandoutView,
    PollListView,
    CreatePollView,
    AddChoiceView
    )

app_name = 'accounts'

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("teacher/request/", RequestTeacherView.as_view(), name="teacher-request"),
    path("teacher/course/craete/", CourseCreateView.as_view(), name="create-course"),
    path("course/", MyCoursesView.as_view(), name="list-courses"),
    path("course/register/<int:course_id>/", MyCoursesView.as_view(), name="register-courses"),
    path("course/delete/<int:pk>/", DeleteCourse.as_view(), name="delete-course"),
    path("course/leave/<int:pk>/", LeaveCourse.as_view(), name="leave-course"),
    path("article/", ArticleListView.as_view(), name="list-articles"),
    path("article/create/", CreateArticleView.as_view(), name="create-article"),
    path("article/delete/<int:pk>/", DeleteArticleView.as_view(), name="delete-article"),
    path("handout/create/", CreateHandoutView.as_view(), name="create-handout"),
    path("poll/", PollListView.as_view(), name="list-poll"),
    path("poll/create/", CreatePollView.as_view(), name="create-poll"),
    path("poll/<int:poll_id>/", AddChoiceView.as_view(), name="add-choice"),
]

home/urls.py
from django.urls import path
from .views import Index,DetailNewsView,NewsListView,DetailArticleView,ArticleListView,HandoutListView,CourseListView,DetailCourseView,DetailPollView

app_name = 'home'

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("news/<int:pk>/", DetailNewsView.as_view(), name="detail-news"),
    path("news/", NewsListView.as_view(), name="list-news"),
    path("article/<int:pk>/", DetailArticleView.as_view(), name="detail-article"),
    path("article/", ArticleListView.as_view(), name="list-article"),
    path("handout/", HandoutListView.as_view(), name="list-handout"),
    path("course/", CourseListView.as_view(), name="list-course"),
    path("course/<int:pk>/", DetailCourseView.as_view(), name="detail-course"),
    path("polls/<int:pk>/", DetailPollView.as_view(), name="detail-poll"),
]

institute_programming/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('account/', include('accounts.urls',namespace='accounts')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.rtl.min.css" integrity="sha384-WJUUqfoMmnfkBLne5uxXj+na/c7sesSJ32gI7GfCk4zO4GthUKhSEGyvQ839BC51" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    
    <title>Institute Programming</title>
</head>

<body>
    <nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary py-3" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home:index' %}">موسسه اموزشی برنامه نویسان</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    
                    {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'accounts:register' %}">ثبت نام</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">ورود</a>
                        </li>
                    {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                حساب کاربری
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">پروفایل</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:list-courses' %}">دوره های شما</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:list-articles' %}">مقالات شما</a></li>
                                {% if request.user.teacher %}
                                <li><a class="dropdown-item" href="{% url 'accounts:create-handout' %}">افزودن جزوه جدید</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:list-poll' %}">نظرسنجی ها</a></li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">خروج</a></li>
                            </ul>
                        </li>
                    {% endif %}
                        
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home:list-handout' %}">جزوات</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home:list-article' %}">مقالات</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home:list-news' %}">اخبار</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home:list-course' %}">دوره ها (دروس)</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    {% block body %}
    {% endblock body %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>

</html>